---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/cs0165/public_html/
    - /bin/cp -R public/assets $DEPLOYPATH
    - /bin/cp -R public/bootstrap $DEPLOYPATH
    - /bin/cp -R public/build $DEPLOYPATH
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/dist $DEPLOYPATH
    - /bin/cp -R public/files $DEPLOYPATH
    - /bin/cp -R public/fonts $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/img $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/plugins $DEPLOYPATH
    - /bin/cp -R public/vendor $DEPLOYPATH
    - /bin/cp -R public/vendors $DEPLOYPATH
    - /bin/cp -R public/word-template $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon.ico $DEPLOYPATH
    - /bin/cp public/mix-manifest.json $DEPLOYPATH
    - /bin/cp public/references.bib $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
    - /bin/cp public/test.bib $DEPLOYPATH
    - /bin/cp public/test.txt $DEPLOYPATH
    - /bin/cp public/web.config $DEPLOYPATH