---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/cs0165/public_html/
    - export PROJECT=/home2/cs0165/Project
    - /bin/rm public/index.php
    - /bin/rm -r $DEPLOYPATH/bootstrap
    - /bin/mv public/bootstrap $DEPLOYPATH/bootstrap
    - /bin/rm -r $DEPLOYPATH/assets
    - /bin/mv public/assets $DEPLOYPATH/assets
    - /bin/rm -r $DEPLOYPATH/build
    - /bin/mv public/build $DEPLOYPATH/build
    - /bin/rm -r $DEPLOYPATH/css
    - /bin/mv public/css $DEPLOYPATH/css
    - /bin/rm -r $DEPLOYPATH/dist
    - /bin/mv public/dist $DEPLOYPATH/dist
    - /bin/rm -r $DEPLOYPATH/files
    - /bin/mv public/files $DEPLOYPATH/files
    - /bin/rm -r $DEPLOYPATH/fonts
    - /bin/mv public/fonts $DEPLOYPATH/fonts
    - /bin/rm -r $DEPLOYPATH/images
    - /bin/mv public/images $DEPLOYPATH/images
    - /bin/rm -r $DEPLOYPATH/img
    - /bin/mv public/img $DEPLOYPATH/img
    - /bin/rm -r $DEPLOYPATH/js
    - /bin/mv public/js $DEPLOYPATH/js
    - /bin/rm -r $DEPLOYPATH/plugins
    - /bin/mv public/plugins $DEPLOYPATH/plugins
    - /bin/rm -r $DEPLOYPATH/vendor
    - /bin/mv public/vendor $DEPLOYPATH/vendor
    - /bin/rm -r $DEPLOYPATH/vendors
    - /bin/mv public/vendors $DEPLOYPATH/vendors
    - /bin/rm -r $DEPLOYPATH/word-template
    - /bin/mv public/word-template $DEPLOYPATH/word-template
    - /bin/mv public/.htaccess $DEPLOYPATH
    - /bin/mv public/favicon.ico $DEPLOYPATH
    - /bin/mv public/mix-manifest.json $DEPLOYPATH
    - /bin/mv public/references.bib $DEPLOYPATH
    - /bin/mv public/robots.txt $DEPLOYPATH
    - /bin/mv public/test.bib $DEPLOYPATH
    - /bin/mv public/test.txt $DEPLOYPATH
    - /bin/mv public/web.config $DEPLOYPATH
    - /bin/unzip vendor.zip
    - /bin/rm vendor.zip
    - /bin/mv app $PROJECT/app
    - /bin/mv bootstrap $PROJECT/bootstrap
    - /bin/mv config $PROJECT/config
    - /bin/mv database $PROJECT/database
    - /bin/mv resources $PROJECT/resources
    - /bin/mv routes $PROJECT/routes
    - /bin/mv storage $PROJECT/storage
    - /bin/mv tests $PROJECT/tests
    - /bin/mv artisan $PROJECT  
    - /bin/mv vendor $PROJECT/vendor
    - /bin/mv composer.json $PROJECT
    - /bin/mv composer.lock $PROJECT
    - /bin/mv package.json $PROJECT
    - /bin/mv webpack.mix.js $PROJECT
    - /bin/mv phpunit.xml $PROJECT
    - /bin/mv server.php $PROJECT
    - /bin/mv .styleci.yml $PROJECT