name: Deploy to cPanel

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cPanel
        id: deploy
        uses: pinkasey/cpanel-deploy-action@v1.0.0
        with:
          hostname: "https://cs0165.cpkkuhost.com"
          repository_root: "/home2/cs0165/repositories/SoftEng-Project-G1S2"
          branch: main
          cpanel_token: ${{ secrets.CPANEL_TOKEN }}
          cpanel_username: "cs0165"
      - name: echo deploy-duration
        run: echo "Deployment took ${{ steps.deploy.outputs.duration }} milliseconds"
